- project:
    templates:
      - openstack-cover-jobs
      - check-requirements
      - openstack-python-jobs
      - openstack-python35-jobs
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-pylint
        - nodepool-functional-py35-redhat-src
        - nodepool-functional-py35-ubuntu-src
    gate:
      jobs:
        - openstack-tox-pylint
        - nodepool-functional-py35-redhat-src
        - nodepool-functional-py35-ubuntu-src
    experimental:
      jobs:
        - nodepool-functional-py35-gentoo-src
        - nodepool-functional-py35-debian-src
        - nodepool-functional-py35-suse-src
        - octavia-v1-dsvm-scenario
        - octavia-v1-dsvm-py3x-scenario
